language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t davidrubiobenito/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true davidrubiobenito/docker-react npm run test
